{
 "title": "API JWT Validator",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instância",
    "query": {
     "query": "label_values(jwt_validation_success_total{instance=\"api-jwt-validator:8080\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "API JWT Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total de Validações de Token com Sucesso",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(jwt_validation_success_total{instance=\"$instance\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Total de Validações de Token com Falha",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(jwt_validation_failure_total{instance=\"$instance\"}[$__range])))"
    }
   ]
  },
  {
   "title": "HTTP Status Code 4xx",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{status=\"400\", uri=\"/api/v1/validate\"}[$__range])"
    }
   ]
  },
  {
   "title": "HTTP Status Code 5xx",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{status=\"500\", uri=\"/api/v1/validate\"}[$__range])"
    }
   ]
  },
  {
   "title": "Validações com Sucesso vs Falha",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "round(sum(increase(jwt_validation_failure_total{instance=\"$instance\"}[$__range])))",
     "legendFormat": "Falha"
    },
    {
     "expr": "round(sum(increase(jwt_validation_success_total{instance=\"$instance\"}[$__range])))",
     "legendFormat": "Sucesso"
    }
   ]
  },
  {
   "title": "Requests Duração",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{instance=\"$instance\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{instance=\"$instance\", status!~\"5..\"}[1m]))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(http_server_requests_seconds_max{instance=\"$instance\", status!~\"5..\"})",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "Requests/Segundos",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"$instance\"}[1m]))",
     "legendFormat": "Requests per second"
    }
   ]
  },
  {
   "title": "Métricas de Sistema",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uso de CPU",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_cpu_usage{instance=\"$instance\"}",
       "legendFormat": "System CPU Usage"
      },
      {
       "expr": "process_cpu_usage{instance=\"$instance\"}",
       "legendFormat": "Process CPU Usage"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memória alocada",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\"}[5m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\"}[5m])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  }
 ]
}